//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurialPlots.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Id { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemName { get; set; }
        public string ItemPicture { get; set; }
        public string ItemQty { get; set; }
        public string ItemPrice { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Member Member { get; set; }
    }
}
