//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurialPlots.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cemetery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cemetery()
        {
            this.CemeteryImages = new HashSet<CemeteryImage>();
            this.MainSections = new HashSet<MainSection>();
        }
    
        public decimal Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string OriginalCode { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> RegionId { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public string Description { get; set; }
        public string KeyInformation { get; set; }
        public string MapLocation { get; set; }
        public string LocationDescription { get; set; }
        public string WhyChoose { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    
        public virtual Origin Origin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CemeteryImage> CemeteryImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainSection> MainSections { get; set; }
    }
}
