//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurialPlots.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CemeteryImage
    {
        public decimal Id { get; set; }
        public string Image { get; set; }
        public string OriginalImage { get; set; }
        public Nullable<decimal> CemeteryId { get; set; }
    
        public virtual Cemetery Cemetery { get; set; }
    }
}
