//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurialPlots.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuneralProduct
    {
        public decimal Id { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public string PrdoctDescription { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> FuneralServiceId { get; set; }
    
        public virtual FuneralService FuneralService { get; set; }
    }
}
