//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurialPlots.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grave
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grave()
        {
            this.CemeteryLayers = new HashSet<CemeteryLayer>();
            this.OrderCemeteries = new HashSet<OrderCemetery>();
        }
    
        public decimal Id { get; set; }
        public string Address { get; set; }
        public string Image { get; set; }
        public string SKU { get; set; }
        public string PlotName { get; set; }
        public string PlotNo { get; set; }
        public string PlotType { get; set; }
        public string Size { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> TierId { get; set; }
        public string ShortDescription { get; set; }
        public string FullDescription { get; set; }
        public string Internement { get; set; }
        public Nullable<decimal> InternementFee { get; set; }
        public string Lease { get; set; }
        public string Maintenance { get; set; }
        public string SpotId { get; set; }
        public Nullable<decimal> SectionId { get; set; }
        public Nullable<decimal> ReligionId { get; set; }
        public Nullable<decimal> SectId { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CemeteryLayer> CemeteryLayers { get; set; }
        public virtual MainSection MainSection { get; set; }
        public virtual Grave Graves1 { get; set; }
        public virtual Grave Grave1 { get; set; }
        public virtual Grave Graves11 { get; set; }
        public virtual Grave Grave2 { get; set; }
        public virtual Relgion Relgion { get; set; }
        public virtual SubRelgion SubRelgion { get; set; }
        public virtual Tier Tier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCemetery> OrderCemeteries { get; set; }
    }
}
