//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurialPlots.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItalianPage
    {
        public decimal Id { get; set; }
        public string Body { get; set; }
        public string PageTittle { get; set; }
        public string Pageurl { get; set; }
        public string FeatureImage { get; set; }
        public string ServiceTitle { get; set; }
    }
}
