//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurialPlots.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MainSection()
        {
            this.Graves = new HashSet<Grave>();
        }
    
        public decimal Id { get; set; }
        public Nullable<decimal> CemeteryId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string OriginalCode { get; set; }
        public string SpotId { get; set; }
        public string Image { get; set; }
    
        public virtual Cemetery Cemetery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grave> Graves { get; set; }
    }
}
