//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurialPlots.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsManagement
    {
        public decimal Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PubDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string TitleUrdu { get; set; }
        public string TitleArabic { get; set; }
        public string TitleChinese { get; set; }
        public string TitleHindi { get; set; }
        public string TitleItalian { get; set; }
        public string TitleBengali { get; set; }
        public string TitleHebrew { get; set; }
        public string DescriptionUrdu { get; set; }
        public string DescriptionArabic { get; set; }
        public string DescriptionChinese { get; set; }
        public string DescriptionHindi { get; set; }
        public string DescriptionItalian { get; set; }
        public string DescriptionBengali { get; set; }
        public string DescriptionHebrew { get; set; }
        public string TitleTurkish { get; set; }
        public string DescriptionTurkish { get; set; }
    }
}
