//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurialPlots.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPlanItem
    {
        public decimal Id { get; set; }
        public Nullable<decimal> OrderPlanId { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> ServiceListingPlanId { get; set; }
    
        public virtual OrderPlan OrderPlan { get; set; }
        public virtual ServiceListingPlan ServiceListingPlan { get; set; }
    }
}
