//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurialPlots.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Page()
        {
            this.PageBoxes = new HashSet<PageBox>();
            this.ServiceBoxes = new HashSet<ServiceBox>();
        }
    
        public int Id { get; set; }
        public string Body { get; set; }
        public string PageTittle { get; set; }
        public string Pageurl { get; set; }
        public string FeatureImage { get; set; }
        public string BodyUrdu { get; set; }
        public string BodyHindi { get; set; }
        public string BodyChinese { get; set; }
        public string BodyArabic { get; set; }
        public string BodyItalian { get; set; }
        public string BodyTurkish { get; set; }
        public string BodyBengali { get; set; }
        public string BodyHebrew { get; set; }
        public string TitleUrdu { get; set; }
        public string TitleHindi { get; set; }
        public string TitleChinese { get; set; }
        public string TitleArabic { get; set; }
        public string TitleItalian { get; set; }
        public string TitleTurkish { get; set; }
        public string TitleBengali { get; set; }
        public string TitleHebrew { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageBox> PageBoxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceBox> ServiceBoxes { get; set; }
    }
}
