//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurialPlots.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageBox
    {
        public int Id { get; set; }
        public Nullable<int> Page { get; set; }
        public Nullable<int> Box { get; set; }
        public Nullable<int> UrduPage { get; set; }
    
        public virtual ServiceBox ServiceBox { get; set; }
        public virtual UrduPage UrduPage1 { get; set; }
        public virtual Page Page1 { get; set; }
    }
}
