//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurialPlots.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopularLocationContent
    {
        public string PopularLocationName { get; set; }
        public string HeaderImage { get; set; }
        public string HeaderText { get; set; }
        public string FirstColHeader { get; set; }
        public string FirstColText { get; set; }
        public string FirstColImage { get; set; }
        public string SecondColHeader { get; set; }
        public string SecondColText { get; set; }
        public string SecondColImage { get; set; }
        public string ThirdColHeader { get; set; }
        public string ThirdColText { get; set; }
        public string ThirdColImage { get; set; }
        public string Step1Header { get; set; }
        public string Step1Message { get; set; }
        public string Step2Header { get; set; }
        public string Step2Message { get; set; }
        public string Step3Header { get; set; }
        public string Step3Message { get; set; }
    }
}
