//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurialPlots.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public decimal Id { get; set; }
        public Nullable<decimal> PartnerId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> ServiceListingId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Member1 Member { get; set; }
        public virtual SeviceListing SeviceListing { get; set; }
        public virtual Partner Partner { get; set; }
    }
}
