//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurialPlots.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceBox
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceBox()
        {
            this.PageBoxes = new HashSet<PageBox>();
        }
    
        public int Id { get; set; }
        public string BoxName { get; set; }
        public string BoxPic { get; set; }
        public Nullable<int> BoxUrl { get; set; }
        public string BoxDescription { get; set; }
        public Nullable<bool> BoxStatus { get; set; }
        public string ServiceUrl { get; set; }
        public Nullable<bool> UrlStatus { get; set; }
        public string BoxNameInUrdu { get; set; }
        public string BoxNameInItalian { get; set; }
    
        public virtual Page Page { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageBox> PageBoxes { get; set; }
    }
}
