//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurialPlots.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceListingPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceListingPlan()
        {
            this.OrderPlanItems = new HashSet<OrderPlanItem>();
        }
    
        public decimal Id { get; set; }
        public Nullable<decimal> CountyId { get; set; }
        public Nullable<decimal> BusinessId { get; set; }
        public Nullable<decimal> PlanId { get; set; }
        public Nullable<decimal> ServiceListId { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual County County { get; set; }
        public virtual FuneralService FuneralService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPlanItem> OrderPlanItems { get; set; }
        public virtual PartnerPlan PartnerPlan { get; set; }
        public virtual SeviceListing SeviceListing { get; set; }
    }
}
