//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurialPlots.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeviceListing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeviceListing()
        {
            this.OrderPlans = new HashSet<OrderPlan>();
            this.Reviews = new HashSet<Review>();
            this.ServiceListingPlans = new HashSet<ServiceListingPlan>();
        }
    
        public decimal Id { get; set; }
        public string BusinessName { get; set; }
        public string PostCode { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string Website { get; set; }
        public string BusinessClassification { get; set; }
        public Nullable<decimal> FuneralServiceId { get; set; }
        public string Picture { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Number { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string ServicesAndProducts { get; set; }
        public string BusinessDescription { get; set; }
        public Nullable<decimal> PartnerId { get; set; }
        public string PaymentGateways { get; set; }
        public string SocialIcons { get; set; }
        public string FacebookLink { get; set; }
        public string TwitterLink { get; set; }
        public string GooglePlusLink { get; set; }
        public string CountiesId { get; set; }
        public string CountiesName { get; set; }
        public Nullable<bool> NationWide { get; set; }
        public string LinkedIn { get; set; }
    
        public virtual FuneralService FuneralService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPlan> OrderPlans { get; set; }
        public virtual Partner Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceListingPlan> ServiceListingPlans { get; set; }
    }
}
