//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurialPlots.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubChlidMenu
    {
        public int Id { get; set; }
        public Nullable<int> MenuId { get; set; }
        public string PageUrl { get; set; }
        public string PageTitle { get; set; }
    
        public virtual submenu submenu { get; set; }
    }
}
