//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurialPlots.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCate
    {
        public decimal Id { get; set; }
        public Nullable<decimal> MainCate { get; set; }
        public string SubName { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
