//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurialPlots.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BurialPlots.Resources.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic
        {
            get
            {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        public static string Italian
        {
            get
            {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        public static string Turkish
        {
            get
            {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        public static string Bengali
        {
            get
            {
                return ResourceManager.GetString("Bengali", resourceCulture);
            }
        }
        public static string Hebrew
        {
            get
            {
                return ResourceManager.GetString("Hebrew", resourceCulture);
            }
        }

        public static string Services
        {
            get
            {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }

        public static string IfYou
        {
            get
            {
                return ResourceManager.GetString("IfYou", resourceCulture);
            }
        }
        public static string DEALINGWITHLOSSOFACHILD
        {
            get
            {
                return ResourceManager.GetString("DEALINGWITHLOSSOFACHILD", resourceCulture);
            }
        }
        public static string OfCourse
        {
            get
            {
                return ResourceManager.GetString("OfCourse", resourceCulture);
            }
        }
        public static string AlthoughCremation
        {
            get
            {
                return ResourceManager.GetString("AlthoughCremation", resourceCulture);
            }
        }
        public static string PRESSNEWS
        {
            get
            {
                return ResourceManager.GetString("PRESSNEWS", resourceCulture);
            }
        }

        public static string ABOUTUS
        {
            get
            {
                return ResourceManager.GetString("ABOUTUS", resourceCulture);
            }
        }
        // Sub Menus
        public static string PROBATE
        {
            get
            {
                return ResourceManager.GetString("PROBATE", resourceCulture);
            }
        }
        public static string Whensomeone
        {
            get
            {
                return ResourceManager.GetString("Whensomeone", resourceCulture);
            }
        }
        public static string Thepositiveaspect
        {
            get
            {
                return ResourceManager.GetString("Thepositiveaspect", resourceCulture);
            }
        }
        public static string Intheimmediate
        {
            get
            {
                return ResourceManager.GetString("Intheimmediate", resourceCulture);
            }
        }
        public static string Planning
        {
            get
            {
                return ResourceManager.GetString("Planning", resourceCulture);
            }
        }
        public static string Thesecondpositive
        {
            get
            {
                return ResourceManager.GetString("Thesecondpositive", resourceCulture);
            }
        }
        public static string Choosing
        {
            get
            {
                return ResourceManager.GetString("Choosing", resourceCulture);
            }
        }
        public static string Choosingtheflowers
        {
            get
            {
                return ResourceManager.GetString("Choosingtheflowers", resourceCulture);
            }
        }
        public static string afloralSprays
        {
            get
            {
                return ResourceManager.GetString("afloralSprays", resourceCulture);
            }
        }
        public static string Wreathsand
        {
            get
            {
                return ResourceManager.GetString("Wreathsand", resourceCulture);
            }
        }
        public static string Tributeswhilst
        {
            get
            {
                return ResourceManager.GetString("Tributeswhilst", resourceCulture);
            }
        }
        public static string Flowersmayseem
        {
            get
            {
                return ResourceManager.GetString("Flowersmayseem", resourceCulture);
            }
        }
        public static string FloralSprays
        {
            get
            {
                return ResourceManager.GetString("FloralSprays", resourceCulture);
            }
        }
        public static string Wreaths
        {
            get
            {
                return ResourceManager.GetString("Wreaths", resourceCulture);
            }
        }
        public static string Tributes
        {
            get
            {
                return ResourceManager.GetString("Tributes", resourceCulture);
            }
        }
        public static string BurialPlotsFlorists
        {
            get
            {
                return ResourceManager.GetString("BurialPlotsFlorists", resourceCulture);
            }
        }

        //Burial Plots Stonemasons Start from here 

        public static string BurialPlotsStonemasons
        {
            get
            {
                return ResourceManager.GetString("BurialPlotsStonemasons", resourceCulture);
            }
        }
        public static string Therole
        {
            get
            {
                return ResourceManager.GetString("Therole", resourceCulture);
            }
        }
        public static string Hereat
        {
            get
            {
                return ResourceManager.GetString("Hereat", resourceCulture);
            }
        }
        public static string TypesofMemorial
        {
            get
            {
                return ResourceManager.GetString("TypesofMemorial", resourceCulture);
            }
        }
        public static string Theroleofastonemason
        {
            get
            {
                return ResourceManager.GetString("Theroleofastonemason", resourceCulture);
            }
        }
        public static string Fullmemorials
        {
            get
            {
                return ResourceManager.GetString("Fullmemorials", resourceCulture);
            }
        }
        public static string alsoknown
        {
            get
            {
                return ResourceManager.GetString("alsoknown", resourceCulture);
            }
        }
        public static string Lawnmemorials
        {
            get
            {
                return ResourceManager.GetString("Lawnmemorials", resourceCulture);
            }
        }
        public static string BurialPlotsPressAndNews
        {
            get
            {
                return ResourceManager.GetString("BurialPlotsPressAndNews", resourceCulture);
            }
        }
        public static string Belowyouwillllfind
        {
            get
            {
                return ResourceManager.GetString("Belowyouwillllfind", resourceCulture);
            }
        }
        public static string PressAndNews
        {
            get
            {
                return ResourceManager.GetString("PressAndNews", resourceCulture);
            }
        }
        public static string thisis
        {
            get
            {
                return ResourceManager.GetString("thisis", resourceCulture);
            }
        }
        public static string BurialPlotsPreNeed
        {
            get
            {
                return ResourceManager.GetString("BurialPlotsPreNeed", resourceCulture);
            }
        }
        public static string Planningfor
        {
            get
            {
                return ResourceManager.GetString("Planningfor", resourceCulture);
            }
        }
        public static string ShortageofBurialPlots
        {
            get
            {
                return ResourceManager.GetString("ShortageofBurialPlots", resourceCulture);
            }
        }
        public static string Inrecentyears
        {
            get
            {
                return ResourceManager.GetString("Inrecentyears", resourceCulture);
            }
        }
        public static string INFORMATIONSUCHAS
        {
            get
            {
                return ResourceManager.GetString("INFORMATIONSUCHAS", resourceCulture);
            }
        }

        public static string ForwardPlanning
        {
            get
            {
                return ResourceManager.GetString("ForwardPlanning", resourceCulture);
            }
        }

        public static string Once
        {
            get
            {
                return ResourceManager.GetString("Once", resourceCulture);
            }
        }
        public static string TheRoyal
        {
            get
            {
                return ResourceManager.GetString("TheRoyal", resourceCulture);
            }
        }
        public static string Searchforaplot
        {
            get
            {
                return ResourceManager.GetString("Searchforaplot", resourceCulture);
            }
        }

        public static string TypesofMaterial
        {
            get
            {
                return ResourceManager.GetString("TypesofMaterial", resourceCulture);
            }
        }
        public static string Thematerial
        {
            get
            {
                return ResourceManager.GetString("Thematerial", resourceCulture);
            }
        }
        public static string Inscription
        {
            get
            {
                return ResourceManager.GetString("Inscription", resourceCulture);
            }
        }
        public static string Whendeciding
        {
            get
            {
                return ResourceManager.GetString("Whendeciding", resourceCulture);
            }
        }
        public static string Engraving
        {
            get
            {
                return ResourceManager.GetString("Engraving", resourceCulture);
            }
        }
        public static string Yourstone
        {
            get
            {
                return ResourceManager.GetString("Yourstone", resourceCulture);
            }
        }
        public static string BurialPlotsWillWriting
        {
            get
            {
                return ResourceManager.GetString("BurialPlotsWillWriting", resourceCulture);
            }
        }
        public static string Writingawill
        {
            get
            {
                return ResourceManager.GetString("Writingawill", resourceCulture);
            }
        }
        public static string Thisisonly
        {
            get
            {
                return ResourceManager.GetString("Thisisonly", resourceCulture);
            }
        }
        public static string Theuse
        {
            get
            {
                return ResourceManager.GetString("Theuse", resourceCulture);
            }
        }
        public static string Yourestate
        {
            get
            {
                return ResourceManager.GetString("Yourestate", resourceCulture);
            }
        }
        public static string Youhave
        {
            get
            {
                return ResourceManager.GetString("Youhave", resourceCulture);
            }
        }
        public static string Youhaveoverseas
        {
            get
            {
                return ResourceManager.GetString("Youhaveoverseas", resourceCulture);
            }
        }
        public static string Youown
        {
            get
            {
                return ResourceManager.GetString("Youown", resourceCulture);
            }
        }
        public static string UsingaSolicitor
        {
            get
            {
                return ResourceManager.GetString("UsingaSolicitor", resourceCulture);
            }
        }
        public static string Ifyouuse
        {
            get
            {
                return ResourceManager.GetString("Ifyouuse", resourceCulture);
            }
        }
        public static string Usingawillwritingservice
        {
            get
            {
                return ResourceManager.GetString("Usingawillwritingservice", resourceCulture);
            }
        }
        public static string Youshould
        {
            get
            {
                return ResourceManager.GetString("Youshould", resourceCulture);
            }
        }
        public static string TheSocietyofWillWriters
        {
            get
            {
                return ResourceManager.GetString("TheSocietyofWillWriters", resourceCulture);
            }
        }
        public static string TheInstitute
        {
            get
            {
                return ResourceManager.GetString("TheInstitute", resourceCulture);
            }
        }
        public static string Membership
        {
            get
            {
                return ResourceManager.GetString("Membership", resourceCulture);
            }
        }
        public static string If
        {
            get
            {
                return ResourceManager.GetString("If", resourceCulture);
            }
        }
        public static string Aftercare
        {
            get
            {
                return ResourceManager.GetString("Aftercare", resourceCulture);
            }
        }
        public static string Onceinplace
        {
            get
            {
                return ResourceManager.GetString("Onceinplace", resourceCulture);
            }
        }
        public static string Designed
        {
            get
            {
                return ResourceManager.GetString("Designed", resourceCulture);
            }
        }

        // FAQS
        public static string FAQS
        {
            get
            {
                return ResourceManager.GetString("FAQS", resourceCulture);
            }
        }
        public static string BurialPlotsFAQS
        {
            get
            {
                return ResourceManager.GetString("BurialPlotsFAQS", resourceCulture);
            }
        }
        public static string HereAtBurialPlotsFAQS
        {
            get
            {
                return ResourceManager.GetString("HereAtBurialPlotsFAQS", resourceCulture);
            }
        }
        public static string DoIhavetowear
        {
            get
            {
                return ResourceManager.GetString("DoIhavetowear", resourceCulture);
            }
        }
        public static string Itstraditional
        {
            get
            {
                return ResourceManager.GetString("Itstraditional", resourceCulture);
            }
        }
        public static string Whoisallowed
        {
            get
            {
                return ResourceManager.GetString("Whoisallowed", resourceCulture);
            }
        }
        public static string Thiswill
        {
            get
            {
                return ResourceManager.GetString("Thiswill", resourceCulture);
            }
        }
        public static string Wheredoes
        {
            get
            {
                return ResourceManager.GetString("Wheredoes", resourceCulture);
            }
        }
        public static string Itistraditional
        {
            get
            {
                return ResourceManager.GetString("Itistraditional", resourceCulture);
            }
        }
        public static string Wheredo
        {
            get
            {
                return ResourceManager.GetString("Wheredo", resourceCulture);
            }
        }
        public static string Thosewhowere
        {
            get
            {
                return ResourceManager.GetString("Thosewhowere", resourceCulture);
            }
        }
        public static string Whatusually
        {
            get
            {
                return ResourceManager.GetString("Whatusually", resourceCulture);
            }
        }
        public static string AfterthefuneralFaq
        {
            get
            {
                return ResourceManager.GetString("AfterthefuneralFaq", resourceCulture);
            }
        }
        public static string Canmournerscarrythecoffin
        {
            get
            {
                return ResourceManager.GetString("Canmournerscarrythecoffin", resourceCulture);
            }

        }
        public static string Friendsorfamily
        {
            get
            {
                return ResourceManager.GetString("Friendsorfamily", resourceCulture);
            }
        }
        public static string Canthefuneral
        {
            get
            {
                return ResourceManager.GetString("Canthefuneral", resourceCulture);
            }
        }
        public static string Thepersonresponsible
        {
            get
            {
                return ResourceManager.GetString("Thepersonresponsible", resourceCulture);
            }
        }
        public static string Canamourner
        {
            get
            {
                return ResourceManager.GetString("Canamourner", resourceCulture);
            }
        }
        public static string FriendsorfamilycanPart
        {
            get
            {
                return ResourceManager.GetString("FriendsorfamilycanPart", resourceCulture);
            }
        }
        public static string CanIput
        {
            get
            {
                return ResourceManager.GetString("CanIput", resourceCulture);
            }
        }
        public static string Yesitperfectly
        {
            get
            {
                return ResourceManager.GetString("Yesitperfectly", resourceCulture);
            }
        }
        public static string Shouldchildren
        {
            get
            {
                return ResourceManager.GetString("Shouldchildren", resourceCulture);
            }
        }
        public static string Ifyoufeel
        {
            get
            {
                return ResourceManager.GetString("Ifyoufeel", resourceCulture);
            }
        }
        public static string Whathappens
        {
            get
            {
                return ResourceManager.GetString("Whathappens", resourceCulture);
            }
        }
        public static string Thedecision
        {
            get
            {
                return ResourceManager.GetString("Thedecision", resourceCulture);
            }
        }
        public static string Whatifthewill
        {
            get
            {
                return ResourceManager.GetString("Whatifthewill", resourceCulture);
            }
        }
        public static string Manywillsoften
        {
            get
            {
                return ResourceManager.GetString("Manywillsoften", resourceCulture);
            }
        }
        public static string DoIneed
        {
            get
            {
                return ResourceManager.GetString("DoIneed", resourceCulture);
            }
        }
        public static string Any
        {
            get
            {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        public static string Publishinganobituary
        {
            get
            {
                return ResourceManager.GetString("Publishinganobituary", resourceCulture);
            }
        }
        //Funerals Start from here 

        public static string BurialPlotsFunerals
        {
            get
            {
                return ResourceManager.GetString("BurialPlotsFunerals", resourceCulture);
            }
        }
        public static string Thefuneral
        {
            get
            {
                return ResourceManager.GetString("Thefuneral", resourceCulture);
            }
        }
        public static string HereatBurialplotscouk
        {
            get
            {
                return ResourceManager.GetString("HereatBurialplots.co.uk", resourceCulture);
            }
        }
        public static string AFuneralDirector
        {
            get
            {
                return ResourceManager.GetString("AFuneralDirector", resourceCulture);
            }
        }
        public static string Inmostcases
        {
            get
            {
                return ResourceManager.GetString("Inmostcases", resourceCulture);
            }
        }
        public static string Whilstthedetails
        {
            get
            {
                return ResourceManager.GetString("Whilstthedetails", resourceCulture);
            }
        }

        public static string Inotherparts
        {
            get
            {
                return ResourceManager.GetString("Inotherparts", resourceCulture);
            }
        }

        //Funeral Directors start from here
        public static string BurialPlotsFuneralDirectors
        {
            get
            {
                return ResourceManager.GetString("BurialPlotsFuneralDirectors", resourceCulture);
            }
        }
        public static string Thepracticalities
        {
            get
            {
                return ResourceManager.GetString("Thepracticalities", resourceCulture);
            }
        }
        public static string Burialplotscoukwascreated
        {
            get
            {
                return ResourceManager.GetString("Burialplotscoukwascreated", resourceCulture);
            }
        }
        public static string Afuneraldirectoris
        {
            get
            {
                return ResourceManager.GetString("Afuneraldirectoris", resourceCulture);
            }
        }
        public static string FuneralDirectors
        {
            get
            {
                return ResourceManager.GetString("Funeral Directors", resourceCulture);
            }
        }
        public static string Foryourown
        {
            get
            {
                return ResourceManager.GetString("Foryourown", resourceCulture);
            }
        }
        public static string NationalAssociation
        {
            get
            {
                return ResourceManager.GetString("NationalAssociation", resourceCulture);
            }
        }
        public static string NationalFederation
        {
            get
            {
                return ResourceManager.GetString("NationalFederation", resourceCulture);
            }
        }
        public static string Society
        {
            get
            {
                return ResourceManager.GetString("Society", resourceCulture);
            }
        }
        public static string Thismeans
        {
            get
            {
                return ResourceManager.GetString("Thismeans", resourceCulture);
            }
        }
        public static string Moving
        {
            get
            {
                return ResourceManager.GetString("Moving", resourceCulture);
            }
        }
        public static string Making
        {
            get
            {
                return ResourceManager.GetString("Making", resourceCulture);
            }
        }
        public static string Placing
        {
            get
            {
                return ResourceManager.GetString("Placing", resourceCulture);
            }
        }
        public static string Dealing
        {
            get
            {
                return ResourceManager.GetString("Dealing", resourceCulture);
            }
        }
        public static string Helping
        {
            get
            {
                return ResourceManager.GetString("Helping", resourceCulture);
            }
        }
        public static string Helpingtoarrange
        {
            get
            {
                return ResourceManager.GetString("Helpingtoarrange", resourceCulture);
            }
        }
        public static string Organising
        {
            get
            {
                return ResourceManager.GetString("Organising", resourceCulture);
            }
        }
        public static string Helpingto
        {
            get
            {
                return ResourceManager.GetString("Helpingto", resourceCulture);
            }
        }
        public static string Nomatter
        {
            get
            {
                return ResourceManager.GetString("Nomatter", resourceCulture);
            }
        }
        public static string Whenchoosing
        {
            get
            {
                return ResourceManager.GetString("Whenchoosing", resourceCulture);
            }
        }
        public static string Whenaskingfor
        {
            get
            {
                return ResourceManager.GetString("Whenaskingfor", resourceCulture);
            }
        }
        public static string Besure
        {
            get
            {
                return ResourceManager.GetString("Besure", resourceCulture);
            }
        }
        public static string Ifyouare
        {
            get
            {
                return ResourceManager.GetString("Ifyouare", resourceCulture);
            }
        }
        public static string Remember
        {
            get
            {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        public static string Funeral
        {
            get
            {
                return ResourceManager.GetString("Funeral", resourceCulture);
            }
        }
        public static string Askfor
        {
            get
            {
                return ResourceManager.GetString("Askfor", resourceCulture);
            }
        }

        //Press and News start from here

        public static string BurialPlotsPressandNews
        {
            get
            {
                return ResourceManager.GetString("BurialPlotsPressandNews", resourceCulture);
            }
        }

        public static string Below
        {
            get
            {
                return ResourceManager.GetString("Below", resourceCulture);
            }
        }
        //Cars Start From Here

        public static string BurialPlotsCars
        {
            get
            {
                return ResourceManager.GetString("BurialPlotsCars", resourceCulture);
            }
        }
        public static string Arrangingthedetails
        {
            get
            {
                return ResourceManager.GetString("Arrangingthedetails", resourceCulture);
            }
        }
        public static string Thehost
        {
            get
            {
                return ResourceManager.GetString("Thehost", resourceCulture);
            }
        }
        public static string Thetime
        {
            get
            {
                return ResourceManager.GetString("Thetime", resourceCulture);
            }
        }
        public static string Help
        {
            get
            {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        public static string Here
        {
            get
            {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        public static string Car
        {
            get
            {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        public static string Thenumber
        {
            get
            {
                return ResourceManager.GetString("Thenumber", resourceCulture);
            }
        }
        public static string OtherOptions
        {
            get
            {
                return ResourceManager.GetString("OtherOptions", resourceCulture);
            }
        }
        public static string Occasionally
        {
            get
            {
                return ResourceManager.GetString("Occasionally", resourceCulture);
            }
        }

        //Coffins Starts from  here

        public static string BurialPlotsCoffins
        {
            get
            {
                return ResourceManager.GetString("BurialPlotsCoffins", resourceCulture);
            }
        }
        public static string Arrangingthefuneral
        {
            get
            {
                return ResourceManager.GetString("Arrangingthefuneral", resourceCulture);
            }
        }
        public static string Inthedays
        {
            get
            {
                return ResourceManager.GetString("Inthedays", resourceCulture);
            }
        }
        public static string Plannin
        {
            get
            {
                return ResourceManager.GetString("Plannin", resourceCulture);
            }
        }
        public static string Choosingall
        {
            get
            {
                return ResourceManager.GetString("Choosingall", resourceCulture);
            }
        }
        public static string Choosingacoffin
        {
            get
            {
                return ResourceManager.GetString("Choosingacoffin", resourceCulture);
            }
        }
        public static string Choices
        {
            get
            {
                return ResourceManager.GetString("Choices", resourceCulture);
            }
        }
        public static string Theinitial
        {
            get
            {
                return ResourceManager.GetString("Theinitial", resourceCulture);
            }
        }
        public static string Inside
        {
            get
            {
                return ResourceManager.GetString("Inside", resourceCulture);
            }
        }
        public static string Choos
        {
            get
            {
                return ResourceManager.GetString("Choos", resourceCulture);
            }
        }

        //LIFEINSURANCE start from here

        public static string BurialPlotsLifeInsurance
        {
            get
            {
                return ResourceManager.GetString("BurialPlotsLifeInsurance", resourceCulture);
            }
        }
        public static string When
        {
            get
            {
                return ResourceManager.GetString("When", resourceCulture);
            }
        }
        public static string Planningof
        {
            get
            {

                return ResourceManager.GetString("Planningof", resourceCulture);
            }
        }
        public static string Anyworries
        {
            get
            {
                return ResourceManager.GetString("Anyworries", resourceCulture);
            }
        }
        public static string Calculating
        {
            get
            {
                return ResourceManager.GetString("Calculating", resourceCulture);
            }
        }
        public static string Choo
        {
            get
            {
                return ResourceManager.GetString("Choo", resourceCulture);
            }
        }
        public static string Different
        {
            get
            {
                return ResourceManager.GetString("Different", resourceCulture);
            }
        }
        public static string Whole
        {
            get
            {
                return ResourceManager.GetString("Whole", resourceCulture);
            }
        }
        public static string thistype
        {
            get
            {
                return ResourceManager.GetString("thistype", resourceCulture);
            }
        }
        public static string thist
        {
            get
            {
                return ResourceManager.GetString("thist", resourceCulture);
            }
        }
        public static string Term
        {
            get
            {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        public static string Itshould
        {
            get
            {
                return ResourceManager.GetString("Itshould", resourceCulture);
            }
        }
        public static string As
        {
            get
            {
                return ResourceManager.GetString("As", resourceCulture);
            }
        }
        public static string Ifyouve
        {
            get
            {
                return ResourceManager.GetString("Ifyouve", resourceCulture);
            }
        }


        //Burial Plots Services starts from here

        public static string BurialPlotsServices
        {
            get
            {
                return ResourceManager.GetString("BurialPlotsServices", resourceCulture);
            }
        }
        public static string Whensomeoneclose
        {
            get
            {
                return ResourceManager.GetString("Whensomeoneclose", resourceCulture);
            }
        }
        public static string Thesecondaspectofbereavement
        {
            get
            {
                return ResourceManager.GetString("Thesecondaspectofbereavement", resourceCulture);
            }
        }
        public static string Burialplotsco
        {
            get
            {
                return ResourceManager.GetString("Burialplotsco", resourceCulture);
            }
        }
        public static string The
        {
            get
            {
                return ResourceManager.GetString("The", resourceCulture);
            }
        }
        public static string Although
        {
            get
            {
                return ResourceManager.GetString("Although", resourceCulture);
            }
        }
        public static string Nomatterwhat
        {
            get
            {
                return ResourceManager.GetString("Nomatterwhat", resourceCulture);
            }
        }


        public static string WRITINGEULAGIES
        {
            get
            {
                return ResourceManager.GetString("WRITINGEULAGIES", resourceCulture);
            }
        }
        public static string HEALINGPROCESS
        {
            get
            {
                return ResourceManager.GetString("HEALINGPROCESS", resourceCulture);
            }
        }
        public static string FUNERALDIRECTORS
        {
            get
            {
                return ResourceManager.GetString("FUNERALDIRECTORS", resourceCulture);
            }
        }
        public static string FUNERALS
        {
            get
            {
                return ResourceManager.GetString("FUNERALS", resourceCulture);
            }
        }
        public static string WhereToStart
        {
            get
            {
                return ResourceManager.GetString("WhereToStart", resourceCulture);
            }
        }

        // Sun menu Variables
        public static string AFTERFUNERAL
        {
            get
            {
                return ResourceManager.GetString("AFTERFUNERAL", resourceCulture);
            }
        }
        public static string MEMORIALS
        {
            get
            {
                return ResourceManager.GetString("MEMORIALS", resourceCulture);
            }
        }
        public static string STONEMASONS
        {
            get
            {
                return ResourceManager.GetString("STONEMASONS", resourceCulture);
            }
        }
        public static string FUNERALPLANS
        {
            get
            {
                return ResourceManager.GetString("FUNERALPLANS", resourceCulture);
            }
        }
        public static string ARRANGING
        {
            get
            {
                return ResourceManager.GetString("ARRANGING", resourceCulture);
            }
        }
        public static string COFFINS
        {
            get
            {
                return ResourceManager.GetString("COFFINS", resourceCulture);
            }
        }
        public static string FLORISTS
        {
            get
            {
                return ResourceManager.GetString("FLORISTS", resourceCulture);
            }
        }
        public static string CARS
        {
            get
            {
                return ResourceManager.GetString("CARS", resourceCulture);
            }
        }
        public static string DEALINGWITHCHILDREN
        {
            get
            {
                return ResourceManager.GetString("DEALINGWITHCHILDREN", resourceCulture);
            }
        }
        public static string PARENTALGRIEF
        {
            get
            {
                return ResourceManager.GetString("PARENTALGRIEF", resourceCulture);
            }
        }
        public static string SHOCKOFSUDDENDEATH
        {
            get
            {
                return ResourceManager.GetString("SHOCKOFSUDDENDEATH", resourceCulture);
            }
        }
        public static string SUICIDE
        {
            get
            {
                return ResourceManager.GetString("SUICIDE", resourceCulture);
            }
        }
        public static string HELPFULORGS
        {
            get
            {
                return ResourceManager.GetString("HELPFULORGS", resourceCulture);
            }

        }
        public static string WILLS
        {
            get
            {
                return ResourceManager.GetString("WILLS", resourceCulture);
            }

        }

        public static string LIFEINSURANCE
        {
            get
            {
                return ResourceManager.GetString("LIFEINSURANCE", resourceCulture);
            }

        }

        public static string WILLWRITING
        {
            get
            {
                return ResourceManager.GetString("WILLWRITING", resourceCulture);
            }

        }

        public static string PRESSCOVERAGE
        {
            get
            {
                return ResourceManager.GetString("PRESSCOVERAGE", resourceCulture);
            }

        }

        public static string NEWSFEED
        {
            get
            {
                return ResourceManager.GetString("NEWSFEED", resourceCulture);
            }

        }

        public static string WHOANDWHY
        {
            get
            {
                return ResourceManager.GetString("WHOANDWHY", resourceCulture);
            }

        }
        public static string TEAM
        {
            get
            {
                return ResourceManager.GetString("TEAM", resourceCulture);
            }

        }

        public static string TESTIMONIALS
        {
            get
            {
                return ResourceManager.GetString("TESTIMONIALS", resourceCulture);
            }

        }



        /// <summary>
        ///   Looks up a localized string similar to At need burial plot purchase.
        /// </summary>
        public static string Atneed
        {
            get
            {
                return ResourceManager.GetString("Atneed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BEREAVEMENT.
        /// </summary>
        public static string BEREAVEMENT
        {
            get
            {
                return ResourceManager.GetString("BEREAVEMENT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BURIAL PLOTS.
        /// </summary>
        public static string BURIALPLOTS
        {
            get
            {
                return ResourceManager.GetString("BURIALPLOTS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BURIAL SPACE IN THE UK COULD.
        /// </summary>
        public static string BURIALSPACEINTHEUKCOULD
        {
            get
            {
                return ResourceManager.GetString("BURIALSPACEINTHEUKCOULD", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string Chinese
        {
            get
            {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CONTACT US.
        /// </summary>
        public static string CONTACTUS
        {
            get
            {
                return ResourceManager.GetString("CONTACTUS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cremation and cremated remains.
        /// </summary>
        public static string Cremationandcrematedremains
        {
            get
            {
                return ResourceManager.GetString("Cremationandcrematedremains", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dealing with the loss of someone close to you is always bound to be a traumatic and difficult experience. On top of the emotional impact of the loss itself, the death of a loved one or close friend also means having to negotiate a complex and daunting set of processes. At the very moment when you feel least equipped to focus on practical, legal or financial issues, you find yourself having to do precisely that..
        /// </summary>
        public static string DealingWith
        {
            get
            {
                return ResourceManager.GetString("DealingWith", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to End of life - A checklist.
        /// </summary>
        public static string Endofifechecklist
        {
            get
            {
                return ResourceManager.GetString("Endofifechecklist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Free 1 Month Listing,Promote Your Business.
        /// </summary>
        public static string Free1MonthListingPromoteYourBusiness
        {
            get
            {
                return ResourceManager.GetString("Free1MonthListingPromoteYourBusiness", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName
        {
            get
            {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Funeral Services List Yours Now.
        /// </summary>
        public static string FuneralServicesListYoursNow
        {
            get
            {
                return ResourceManager.GetString("FuneralServicesListYoursNow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HELPFUL ADVICE.
        /// </summary>
        public static string HELPFULADVICE
        {
            get
            {
                return ResourceManager.GetString("HELPFULADVICE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Here at Burialplots.co.uk we set out to minimise the stress which all of this involves by doing two things. The first of these is to offer access to affordable burial plots across the UK, bringing choice, flexibility and convenience to a market place which is currently failing to meet demand. The second is to provide a source of information and help to anyone who finds themselves having to arrange a funeral, or wishes to remove uncertainty by making plans for the future..
        /// </summary>
        public static string HereatBurialPlots
        {
            get
            {
                return ResourceManager.GetString("HereatBurialPlots", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hindi.
        /// </summary>
        public static string Hindi
        {
            get
            {
                return ResourceManager.GetString("Hindi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lang.
        /// </summary>
        public static string LANGUAGE
        {
            get
            {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LATEST NEWS.
        /// </summary>
        public static string LATESTNEWS
        {
            get
            {
                return ResourceManager.GetString("LATESTNEWS", resourceCulture);
            }
        }

        public static string FirstName
        {
            get
            {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        public static string SignUpAsPartner
        {
            get
            {
                return ResourceManager.GetString("SignUpAsPartner", resourceCulture);
            }
        }
        public static string AlreadyHaveAnAccount
        {
            get
            {
                return ResourceManager.GetString("AlreadyHaveAnAccount", resourceCulture);
            }
        }
        public static string ClickHere
        {
            get
            {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        public static string LastName
        {
            get
            {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to LEGAL.
        /// </summary>
        public static string LEGAL
        {
            get
            {
                return ResourceManager.GetString("LEGAL", resourceCulture);
            }
        }
        public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        public static string ConfirmPassword
        {
            get
            {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        public static string TelephoneNumber
        {
            get
            {
                return ResourceManager.GetString("TelephoneNumber", resourceCulture);
            }
        }
        public static string Signup
        {
            get
            {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to List Your Cemetery Plots.
        /// </summary>
        public static string ListYourCemeteryPlots
        {
            get
            {
                return ResourceManager.GetString("ListYourCemeteryPlots", resourceCulture);
            }
        }
        public static string Login
        {
            get
            {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        public static string ForgotYourPassword
        {
            get
            {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        public static string Recover
        {
            get
            {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        public static string EnterEmailForRecovery
        {
            get
            {
                return ResourceManager.GetString("EnterEmailForRecovery", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to logo.png.
        /// </summary>
        public static string logopng
        {
            get
            {
                return ResourceManager.GetString("logopng", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message
        {
            get
            {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MORE.
        /// </summary>
        public static string MORE
        {
            get
            {
                return ResourceManager.GetString("MORE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Planning ahead.
        /// </summary>
        public static string Planningahead
        {
            get
            {
                return ResourceManager.GetString("Planningahead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pre need burial plot purchase.
        /// </summary>
        public static string Preneed
        {
            get
            {
                return ResourceManager.GetString("Preneed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RUN OUT WITHIN THE NEXT 20 YEARS.
        /// </summary>
        public static string RUNOUTWITHINTHENEXT20YEARS
        {
            get
            {
                return ResourceManager.GetString("RUNOUTWITHINTHENEXT20YEARS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign Up Now.
        /// </summary>
        public static string SignUpNow
        {
            get
            {
                return ResourceManager.GetString("SignUpNow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign up Today and get a call back from us.
        /// </summary>
        public static string SignupTodayandgetacallbackfromus
        {
            get
            {
                return ResourceManager.GetString("SignupTodayandgetacallbackfromus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit
        {
            get
            {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone
        {
            get
            {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Urdu.
        /// </summary>
        public static string Urdu
        {
            get
            {
                return ResourceManager.GetString("Urdu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We’d love to hear from you.
        /// </summary>
        public static string Wedidhear
        {
            get
            {
                return ResourceManager.GetString("Wedidhear", resourceCulture);
            }
        }
    }
}
